### ISSUE TITLE
Got an uncaught exception on the Chromecast subsystem

### ISSUE THREAD

**Issue by jbfavre** [vincentbernat/dashkiosk#17]
Hello,
Got this error with lastest version of Dashkiosk.
I'm running it on Debian Wheezy and nodejs 0.10.33 from Joyent.

That does not prevent Dashkiosk to run, but maybe it could explain connexion loss I got from time to time with Chromecast devices ?

Regards,
JB

```
error: Got an uncaught exception on the Chromecast subsystem 
{ stack: 
   [ 'Error: dns service error: unknown',
     '    at MDNSService.on_resolver_done (/var/www/node_modules/nodecastor/node_modules/mdns2/lib/resolver_sequence_tasks.js:19:30)',
     '    at SocketWatcher.MDNSService.self.watcher.callback (/var/www/node_modules/nodecastor/node_modules/mdns2/lib/mdns_service.js:17:38)' ],
  message: 'dns service error: unknown',
  errorCode: -65537,
  domainEmitter: 
   { domain: 
      { domain: null,
        _events: { error: [Function] },
        _maxListeners: 10,
        members: [] },
     _events: 
      { serviceUp: [Function: onServiceUp],
        serviceDown: [Function: onServiceDown] },
     _maxListeners: 10,
     _watcherStarted: true,
     serviceRef: { initialized: true, fd: 13 },
     watcher: 
      { host: { '$ref': '$["domainEmitter"]' },
        callback: [Function] } },
  domain: { '$ref': '$["domainEmitter"]["domain"]' },
  domainThrown: false }
```

**Comment by vincentbernat** [comment]
@jbfavre Do you still have the problem?

**Comment by jbfavre** [comment]
did not pay specific attention to it. Still have to test mdns2 replacement though.

**Comment by jbfavre** [comment]
did not pay specific attention to it. Still have to test mdns2 replacement though.
Will try to do it next week.

**Comment by jbfavre** [comment]
did not pay specific attention to it. Still have to test mdns2 replacement though.
Will try to do it next week.
