### ISSUE TITLE
chromecast: nodecastor module wont build due to error

### ISSUE THREAD

**Issue by zerog2k** [vincentbernat/dashkiosk#33]
encountered this error on both ubuntu 15.04 and debian wheezy.
Seems like nodecastor fails to build because mdns module doesnt build due to missing headers/dev pkgs at:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory

```
~/dashkiosk-2.6.4/dist$ npm install nodecastor
 
> mdns@2.2.10 install /home/jens/dashkiosk-2.6.4/dist/node_modules/nodecastor/node_modules/mdns
> node-gyp rebuild

make: Entering directory `/home/jens/dashkiosk-2.6.4/dist/node_modules/nodecastor/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory `/home/jens/dashkiosk-2.6.4/dist/node_modules/nodecastor/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jens/dashkiosk-2.6.4/dist/node_modules/nodecastor/node_modules/mdns
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN optional dep failed, continuing nodecastor@0.1.7
```

solution seems to be to install libavahi-compat-libdnssd-dev:
```
sudo apt-get install libavahi-compat-libdnssd-dev
```

and then rebuild:
```
npm install
```

note that it does log the following warning at startup, but still seems basically functional on chromecast:
```
~/dashkiosk-2.6.4/dist$ nodejs server.js
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
```

**Comment by vincentbernat** [comment]
Yes, libavahi-compat-libdnssd-dev is needed to build the mdns module. There is no way to express that directly in npm. This is specified in the documentation.

As for the warning, it is also expected on Linux. mdns still uses the "old" API because OS X doesn't have the new one.

**Comment by vincentbernat** [comment]
I have added a word about the warning in the documentation since it may worry other people.

**Comment by zerog2k** [comment]
Thanks @vincentbernat - it's great software!
