### ISSUE TITLE
Uncaught exception on the Chromecast subsystem -> Error: getaddrinfo -16

### ISSUE THREAD

**Issue by Costa-24** [vincentbernat/dashkiosk#84]
Hi,

I'm running Dashkiosk on a CentOS VM with the intention of controlling a network of Chromecasts and get the following when I try to run the server with the Chromecast module enabled...

    2019-05-06T14:05:49.027Z - error: Got an uncaught exception on the Chromecast subsystem
    { stack:
       [ 'Error: getaddrinfo -16',
         '    at errnoException (/opt/dashkiosk/dashkiosk-2.7.3/dist/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)',
         '    at getaddrinfo_complete (/opt/dashkiosk/dashkiosk-2.7.3/dist/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)',
         '    at GetAddrInfoReqWrap.oncomplete (/opt/dashkiosk/dashkiosk-2.7.3/dist/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)' ],
      message: 'getaddrinfo -16',
      code: -16,
      errno: -16,
      syscall: 'getaddrinfo',
      domainEmitter:
       { domain:
          { domain: null,
            _events: { error: [Function] },
            _eventsCount: 1,
            _maxListeners: undefined,
            members: [] },
         _events:
          { serviceUp: [Function: onServiceUp],
            serviceDown: [Function: onServiceDown] },
         _eventsCount: 2,
         _maxListeners: undefined,
         _watcherStarted: true,
         serviceRef: { initialized: true, fd: 14 },
         watcher: { host: { '$ref': '$["domainEmitter"]' }, callback: [Function] } },
      domain: { '$ref': '$["domainEmitter"]["domain"]' },
      domainThrown: false }

I've seen that there are a couple of other issues logged about uncaught exceptions in the Chromecast module, but none of them seem to actually have the same error in the stack trace. I tried following the instructions in those threads nonetheless but didn't find anything that solved the issue. I also tried looking up the faulting call (getaddrinfo) on Google, but everywhere I looked I saw only up to 12 error codes, yet the error above says code 16.

I appreciate any help, let me know if there's any other info needed.

**Comment by vincentbernat** [comment]
Errno 16 is `EBUSY`. It doesn't make much sense. If it's an GAI error, on my system, 16 is not known either. Does `avahi-browse -a -r` shows anything suspicious? The Chromecasts should appear here with both `hostname =` and `address =`.

Alternatively, you may try to upgrade `mdns` library to 2.4.0. Maybe there is a bug here that could be solved.

**Comment by Costa-24** [comment]
Sorry for the delay in replying.

I do see the devices in the avahi-browse output...
    = enp0s3 IPv4 Chromecast-Ultra-630a0e72973aa9ba9b9220df8f0cbff1 _googlecast._tcp     local
       hostname = [630a0e72-973a-a9ba-9b92-20df8f0cbff1.local]
       address = [10.200.156.209]
       port = [8009]
       txt = ["rs=" "nf=1" "bs=FA8FCA6951E9" "st=0" "ca=200709" "fn=R&D Arch TV" "ic=/setup/icon.png" "md=Chromecast Ultra" "ve=05" "rm=3F33104FDDCD8443" "cd=011ACDA5776CDCD7265D87EF2C2706FF" "id=630a0e72973aa9ba9b9220df8f0cbff1"]

Also a detail to add in case it helps investigating, the getaddrinfo error appears once for each Chromecast on our network (there are 8 in total).

For the mdns lib version, I believe it's already 2.4.0...
    [dashkiosk@dashkiosk dist]$ npm list mdns
    dashkiosk@2.7.3 /opt/dashkiosk/dashkiosk-2.7.3/dist
    └─┬ nodecastor@0.1.8
      └── mdns@2.4.0

**Comment by Costa-24** [comment]
The CentOS version is 7.6.1810, with Linux kernel version 3.10.0-957

I'm afraid I'm going to need a little more help with your second request :P Forgive my cluelessness.

I've tried inserting that console output call in a few spots in and around the line numbers referenced by the above stack (line 120 primarily, but also tried 199, 112). When I try in and around the function containing the call on line 120, I get errors because "service" is not defined in that scope. When I try around 199 or 112, the server just skips trying to enable the Chromecast module altogether "due to an error when importing `nodecastor'"

**Comment by vincentbernat** [comment]
Sorry for the late answer, I missed your answer.

At line 119, before `req.oncomplete = ...`, could you add:

```js
console.log("getaddrinfo:", err, req, host, family);
```

The function should look like this:

```js
function getaddrinfo_0_11(host, family, cb) {
    var req = new cares.GetAddrInfoReqWrap()
      , err = cares.getaddrinfo(req, host, family, 0, false)
      ;
    console.log("getaddrinfo:", err, req, host, family);
    req.oncomplete = function oncomplete(err, addresses) {
        getaddrinfo_complete(err, addresses, cb);
    }
    if (err) throw errnoException(err, 'getaddrinfo', host);
}
```
