### ISSUE TITLE
Can't connect to postgres

### ISSUE THREAD

**Issue by puco** [vincentbernat/dashkiosk#85]
While trying to setup dashkiosk to store it's state in postgres I got the following error:

```
error: unable to register new display
{ stack:
   [ 'error: password authentication failed for user "dashkiosk"',
     '    at Connection.parseE (/dashkiosk/dist/node_modules/pg/lib/connection.js:539:11)',
     '    at Connection.parseMessage (/dashkiosk/dist/node_modules/pg/lib/connection.js:366:17)',
     '    at Socket.<anonymous> (/dashkiosk/dist/node_modules/pg/lib/connection.js:105:22)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at TCP.onread (net.js:559:20)' ],
  message: 'password authentication failed for user "dashkiosk"',
  name: 'error',
  length: 105,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '328',
  routine: 'auth_failed' }
```

The target is a not so recent PostgreSQL 10.6 running on AWS RDS. I think upgrading the quite outdated `pg` package might help with this issue.

**Comment by vincentbernat** [comment]
Can you try? You just need to do `npm update pg`.

**Comment by vincentbernat** [comment]
It seems updating pg fixes the issue. You can try 2.7.7 if you want. Reopen if the issue is still here.
