### ISSUE TITLE
problems with the directory structure after the setup

### ISSUE THREAD

**Issue by dothebart** [vincentbernat/dashkiosk#98]
I've built the dashkiosk the way described in the documentation on an Armbian based debian machine. 
However, for me it all ended in a `build` directory. 
It seems that the directory structure is not as expected. I get this: 

```
{"req":{"url":"/receiver","headers":{"host":"192.168.178.249","connection":"keep-alive","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,de;q=0.8"},"method":"GET","httpVersion":"1.1","originalUrl":"/receiver","query":{}},"res":{"statusCode":500},"responseTime":5,"level":"info","message":"HTTP GET /receiver"}
Error: Failed to lookup view "receiver" in views directory "/root/dashkiosk-2.7.8/public"
    at Function.render (/root/dashkiosk-2.7.8/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/root/dashkiosk-2.7.8/node_modules/express/lib/response.js:961:7)
    at /root/dashkiosk-2.7.8/lib/express.js:82:9
    at Layer.handle [as handle_request] (/root/dashkiosk-2.7.8/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/dashkiosk-2.7.8/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/root/dashkiosk-2.7.8/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/dashkiosk-2.7.8/node_modules/express/lib/router/layer.js:95:5)
    at /root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:330:12)
    at next (/root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/root/dashkiosk-2.7.8/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:312:13)
    at /root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:330:12)
    at next (/root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:271:10)
    at /root/dashkiosk-2.7.8/node_modules/express-winston/index.js:258:9
```

and that: 
```
{"req":{"url":"/admin","headers":{"host":"192.168.178.249","connection":"keep-alive","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,de;q=0.8"},"method":"GET","httpVersion":"1.1","originalUrl":"/admin","query":{}},"res":{"statusCode":500},"responseTime":7,"level":"info","message":"HTTP GET /admin"}
Error: Failed to lookup view "admin" in views directory "/root/dashkiosk-2.7.8/public"
    at Function.render (/root/dashkiosk-2.7.8/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/root/dashkiosk-2.7.8/node_modules/express/lib/response.js:961:7)
    at /root/dashkiosk-2.7.8/lib/express.js:82:9
    at Layer.handle [as handle_request] (/root/dashkiosk-2.7.8/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/dashkiosk-2.7.8/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/root/dashkiosk-2.7.8/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/dashkiosk-2.7.8/node_modules/express/lib/router/layer.js:95:5)
    at /root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:330:12)
    at next (/root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/root/dashkiosk-2.7.8/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:312:13)
    at /root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:330:12)
    at next (/root/dashkiosk-2.7.8/node_modules/express/lib/router/index.js:271:10)
    at /root/dashkiosk-2.7.8/node_modules/express-winston/index.js:258:9
```
there also is no server.js installed into `build`, so I started doing some symlinks. 

For some reason it seems it intends to have a `public` directory instead of `dist` or `build` - joining them seems to get me a working instance.

**Comment by vincentbernat** [comment]
For some reason, I forgot about this...

The `public` directory should be inside `dist`, as well as the `server.js` file.
