### ISSUE TITLE
chromecast ultra doesn't show up in admin screen

### ISSUE THREAD

**Issue by dothebart** [vincentbernat/dashkiosk#99]
Though I see `"level":"info","message":"Rescan Chromecast devices"` and 
```
avahi-browse _googlecast._tcp
+   eth0 IPv4 Chromecast-Ultra-406091bcc5c70cacbca945e5370f9395 _googlecast._tcp     local
```
is able to see it, it won't show up in the admin screen. 
Is there a way to get more information here?

**Comment by vincentbernat** [comment]
What does `./node_modules/nodecastor/bin/nodecastor discover` says?

**Comment by dothebart** [comment]
hm, its not there :/

**Comment by dothebart** [comment]
its actually: 
```
./node_modules/nodecastor/bin/chromecast discover 
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo -3008
    at errnoException (/root/dashkiosk-2.7.8/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/root/dashkiosk-2.7.8/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/root/dashkiosk-2.7.8/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
Emitted 'error' event at:
    at on_resolver_done (/root/dashkiosk-2.7.8/node_modules/mdns/lib/browser.js:28:14)
    at next (/root/dashkiosk-2.7.8/node_modules/mdns/lib/browser.js:100:7)
    at /root/dashkiosk-2.7.8/node_modules/mdns/lib/resolver_sequence_tasks.js:160:11
    at getaddrinfo_complete (/root/dashkiosk-2.7.8/node_modules/mdns/lib/resolver_sequence_tasks.js:112:7)
    at GetAddrInfoReqWrap.oncomplete (/root/dashkiosk-2.7.8/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
```

**Comment by dothebart** [comment]
ok, solved, thanks to 


edited the `/etc/nsswitch.conf` which was missing on that machine to contain 
`files mdns4_minimal [NOTFOUND=return] dns mymachines mdns4`
and 
```
apt-get install libnss-mdns
```
https://github.com/superhawk610/multicast/issues/23 had this.

**Comment by dothebart** [comment]
ok, restarting the server then made it work.

**Comment by dothebart** [comment]
Maybe system misconfiguration should be somehow better anounced in the logs, but I think this issue can be closed.
